project:
  type: website
  output-dir: docs
  
website: "tsbanister.github.io/BIO806Website/"
  title: "Trevor Banister"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/tsbanister/BIO806Website.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Trevor Banister"

format:
  html:
    theme: lux
    toc: true

editor: source

